package com.example.greendao_retrofit.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.greendao_retrofit.bean.NewsListBean;

import com.example.greendao_retrofit.dao.NewsListBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsListBeanDaoConfig;

    private final NewsListBeanDao newsListBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsListBeanDaoConfig = daoConfigMap.get(NewsListBeanDao.class).clone();
        newsListBeanDaoConfig.initIdentityScope(type);

        newsListBeanDao = new NewsListBeanDao(newsListBeanDaoConfig, this);

        registerDao(NewsListBean.class, newsListBeanDao);
    }
    
    public void clear() {
        newsListBeanDaoConfig.clearIdentityScope();
    }

    public NewsListBeanDao getNewsListBeanDao() {
        return newsListBeanDao;
    }

}
