package example.com.sousuodome.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import example.com.sousuodome.greendao.SelectGreenDaoBean;

import example.com.sousuodome.greendao.SelectGreenDaoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig selectGreenDaoBeanDaoConfig;

    private final SelectGreenDaoBeanDao selectGreenDaoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        selectGreenDaoBeanDaoConfig = daoConfigMap.get(SelectGreenDaoBeanDao.class).clone();
        selectGreenDaoBeanDaoConfig.initIdentityScope(type);

        selectGreenDaoBeanDao = new SelectGreenDaoBeanDao(selectGreenDaoBeanDaoConfig, this);

        registerDao(SelectGreenDaoBean.class, selectGreenDaoBeanDao);
    }
    
    public void clear() {
        selectGreenDaoBeanDaoConfig.clearIdentityScope();
    }

    public SelectGreenDaoBeanDao getSelectGreenDaoBeanDao() {
        return selectGreenDaoBeanDao;
    }

}
